services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=errors
    ports:
      - "3306:3306"